
### CREATE
POST http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
  "firstname": "s",
  "lastname": "s",
  "username": "yarensu",
  "email": "yaren@hotmail.com",
  "phone": "05357654944",
  "password": "ssccdzxv"
}
###