### GET request to example server
GET http://localhost:8080/users/health
Content-Type: application/json


###POST AUTH
POST http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
  "firstname": "alperen",
  "lastname": "emin",
  "username": "alprn",
  "email": "alprnemn@hotmail.com",
  "phone": "05357343434",
  "password": "asdasdasd"
}

###POST AUTH
GET http://127.0.0.1:8080/auth/login
Content-Type: application/json

