### GET request to example server
GET http://localhost:8080/users/health
Content-Type: application/json


###POST AUTH
POST http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
  "firstname": "alperen",
  "lastname": "emin",
  "username": "alprn",
  "email": "alprnemn@hotmail.com",
  "phone": "05357343434",
  "password": "asdasdasd"
}

### post actıvate user
GET http://127.0.0.1:8080/auth/activate?token=ea233a93-3615-4e7f-8623-7c4339974684



###POST AUTH
PATCH http://127.0.0.1:8081/user/activate
Content-Type: application/json

{
  "userid" : "106fc317-03eb-46ba-b96b-1cf81b4cf1d4"
}
